### ISSUE TITLE
Returns: Falling commodity prices results in error

### ISSUE THREAD

**Issue by redstreet** [beancount/beangrow#4]
Input:
```
plugin "beancount.plugins.auto_accounts"
plugin "beancount.plugins.implicit_prices"

2005-01-01 commodity ABCD

2019-12-01 * "Buy"
  Assets:Investments  100 ABCD {45 USD}
  Assets:Bank

2020-01-01 price ABCD 35 USD
```

Config:
```
investments {
  investment {
    currency: "ABCD"
    asset_account: "Assets:Investments"
    cash_accounts: "Assets:Bank"
  }
}


groups {
  group {
    name: "test"
    investment: "Assets:Investments"
    }
}
```

Expected: negative returns rate. Observed:
```
beanlabs/returns/returns.py:63: RuntimeWarning: invalid value encountered in power
return np.sum(cash_flows / (1. + irr) ** years)
```

and `20.0%` for the returns for 2019 (in index.html), showing that the solver (`np.sum()` call) failed.

Works fine if the price remains the same or goes up. Example:
```
2020-01-01 price ABCD 50 USD
```

**Comment by gety9** [comment]
I solved "RuntimeWarning: invalid value encountered in power" message by replacing https://github.com/beancount/beangrow/blob/master/beangrow/returns.py#L63 with `return np.sum(cash_flows / (np.sign(1. + irr) * (np.abs(1. + irr)) ** years))`
(explanation https://stackoverflow.com/a/45384691)

After that 2019's return for your test file was showing as `-105.2%`
which is better than 20% but still not accurate enough, it caused by poor initial estimate at https://github.com/beancount/beangrow/blob/master/beangrow/returns.py#L85
by improving it just a little bit with
```
    # Start with something reasonably normal.
    if np.sum(cash_flows) > 0:
        estimated_irr = 0.2
    elif np.sum(cash_flows) < 0:
        estimated_irr = -0.2
    else:
        estimated_irr = 0
```
we get 2019's return of `-94.8%` which is same as calculated by https://www.rateofreturnexpert.com/time-weighted-return-calculator/

**Comment by ThomasdenH** [comment]
Great find!

Your code snippet for the estimate can be shortened by using

```python
estimated_irr = 0.2 * np.sign(np.sum(cash_flows))
```
